server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1    #\u91C7\u96C6\u7387100\uFF0C\u751F\u4EA7\u73AF\u588310%

  thymeleaf:
    cache: false
  redis:
    host: 192.168.194.129
  rabbitmq:
    host: 192.168.194.129
    virtual-host: /springtest
    username: lxm
    password: lxm
    publisher-confirm-type: CORRELATED
    publisher-returns: true
feign:
  sentinel:
    enabled: true