server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1    #\u91C7\u96C6\u7387100\uFF0C\u751F\u4EA7\u73AF\u588310%

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.194.129:3306/guli_cart
    username: root
    password: 123456
  redis:
    host: 192.168.194.129
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.194.129
    virtual-host: /springtest
    username: lxm
    password: lxm
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: E:\abc\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: user-key
    expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto