server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1    #\u91C7\u96C6\u7387100\uFF0C\u751F\u4EA7\u73AF\u588310%

  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: E:\abc\rsa\rsa.pub
    priKeyPath: E:\abc\rsa\rsa.pri
    secret: hjskJKL16531*#hjkHgai354
    expire: 180
    cookieName: GMALL-TOKEN
    unick: unick
