server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1    #\u91C7\u96C6\u7387100\uFF0C\u751F\u4EA7\u73AF\u588310%
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.194.129:3306/guli_ums
    username: root
    password: 123456
  redis:
    host: 192.168.194.129
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto
